```yaml id="m8n7b6"
applications:
  app:
    source:
      root: "/"

    type: "nodejs:20"

    build:
      flavor: none

    hooks:
      build: |
        set -ex
        npm install

    web:
      commands:
        start: node index.js

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
```
