```yaml id="p7q8r9"
applications:
  app:
    source:
      root: "/"

    type: "nodejs:20"

    web:
      commands:
        start: node index.js

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
```
