```yaml id="o3fj7h"
applications:
  myapp:
    type: 'nodejs:22'

    hooks:
      build: 'npm install && npm run build'

    web:
      commands:
        start: 'npm start'

services:
  db:
    type: 'postgresql:16'

routes:
  'https://{default}/':
    type: upstream
    upstream: 'myapp:http'
```
